repository, migrations, settings added
Kalasouski/UserService pull request #1
Opened 2022-08-04 07:09 UTC by Kalasouski

2022-08-05 09:13 UTC, DrGermanius requested changes

2022-08-05 09:13 UTC, DrGermanius commented on cmd/main.go
> +	"userservice/internal/settings"
please use goimports for sorting(u can set up it in your ide)

2022-08-05 09:13 UTC, DrGermanius commented on internal/migrations/20220804091629_userdb.sql
> +    Email   varchar(32),
email must be unique too

2022-08-05 09:13 UTC, DrGermanius commented on internal/migrations/20220804091629_userdb.sql
> +    Password    varchar(256)
please add CreatedAt, UpdatedAt fields

2022-08-05 09:13 UTC, DrGermanius commented on internal/migrations/migration.go
> +}
is it will work inside of docker container?

2022-08-05 09:13 UTC, DrGermanius commented on internal/settings/settings.go
> +		SSLMode:  os.Getenv("SSLMODE")}
what will happen if one of these envs is not set?

2022-08-05 11:30 UTC, Kalasouski commented on internal/migrations/migration.go
> +}
yes, it works

2022-08-10 10:51 UTC, DrGermanius requested changes

2022-08-10 10:51 UTC, DrGermanius commented on cmd/main.go
> +	err = router.Run(":8080")
let's move this port to appSettings

2022-08-10 10:51 UTC, DrGermanius commented on internal/handlers/handlers.go
> +		ctx.JSON(400, gin.H{
Why 400 ?

2022-08-10 10:51 UTC, DrGermanius commented on internal/migrations/20220808115101_userdb.sql
> +    EXECUTE PROCEDURE trigger_set_timestamp();
where did you find that ?

2022-08-11 08:00 UTC, Kalasouski commented on internal/migrations/20220808115101_userdb.sql
> +    EXECUTE PROCEDURE trigger_set_timestamp();
> where did you find that ?
I googled "postgesql updatedat triggers"

2022-08-11 08:41 UTC, Kalasouski commented on internal/handlers/handlers.go
> +		ctx.JSON(400, gin.H{
Fixed in new commit. I left 400 where I'm not sure which code is more appropriate

2022-08-11 17:33 UTC, DrGermanius requested changes

2022-08-11 17:33 UTC, DrGermanius commented on internal/handlers/handlers.go
> +		ctx.Abort()
investigate how to remove gin.H{} from responses.

2022-08-11 17:33 UTC, DrGermanius commented on internal/handlers/handlers.go
> +func (h Handler) tokenMiddleware(ctx *gin.Context) {
let's move it to middlewares package or file

2022-08-11 17:33 UTC, DrGermanius commented on internal/handlers/handlers.go
> +		return
please create a function with mapping "your errors -> status codes"

2022-08-11 17:33 UTC, DrGermanius commented on internal/models/auth.go
> +}
please add validation tags

2022-08-11 17:33 UTC, DrGermanius commented on internal/services/service.go
> +		key := settings.GetenvDefault("JWT_SECRET", "my-32-character-ultra-secure-and-ultra-long-secret")
meh

2022-08-13 14:23 UTC, DrGermanius commented on internal/handlers/auth_handlers.go
> +)
please use "go imports"

2022-08-13 14:23 UTC, DrGermanius commented on internal/handlers/auth_handlers.go
> +			responses.NewServerRequestError(fmt.Sprintf("Something went wrong during registering: %v", err)))
very verbose

2022-08-13 14:23 UTC, DrGermanius commented on internal/handlers/handlers.go
> +	claims, _ := ctx.Get("Claims")
err ignoring?

2022-08-13 14:23 UTC, DrGermanius commented on internal/handlers/middlewares.go
> +		ctx.Abort()
i believe you don't need to do ctx.Abort()

2022-08-13 14:23 UTC, DrGermanius commented on internal/usererrors/errors.go
> +		return http.StatusBadRequest
better to return 500

2022-08-13 14:23 UTC, DrGermanius commented on internal/usererrors/errors.go
> +}
you can just init a map

var m := map[aaa]vvv {
.. values ....
 }

2022-08-13 14:23 UTC, DrGermanius commented on internal/services/service.go
> +	}
finally you lose your err and you don't know what happens

2022-08-16 08:51 UTC, Kalasouski commented on internal/handlers/middlewares.go
> +		ctx.Abort()
If I remove abort call then thenext handler function will be executed

2022-08-17 17:19 UTC, DrGermanius requested changes

2022-08-17 17:19 UTC, DrGermanius commented on internal/handlers/middlewares.go
> +		ctx.Abort()
you're right
let's use the c.AbortWithStatus() or AbortWIthJSON instead. Looks more clear

2022-08-22 19:14 UTC, merged