Feature/mongolog
Kalasouski/UserService pull request #2
Opened 2022-08-17 08:13 UTC by Kalasouski

2022-08-17 16:59 UTC, DrGermanius requested changes

2022-08-17 16:59 UTC, DrGermanius commented on internal/handlers/auth_handlers.go
> +		h.sendErrorResponse(ctx, usererrors.ErrorToCode(err), responses.NewServerRequestError(fmt.Sprint(err)))
what is the purpose of fmt.Sprint() ?

2022-08-17 16:59 UTC, DrGermanius commented on internal/logger/logger.go
> +	uri := "mongodb://" + s.Host + ":" + s.Port
better to use Sprintf

2022-08-17 16:59 UTC, DrGermanius commented on internal/logger/logger.go
> +		log.Fatal(err)
why log.Fatal?

2022-08-17 16:59 UTC, DrGermanius commented on internal/logger/logger.go
> +		log.Fatal(err)
better to return the err

2022-08-18 10:55 UTC, DrGermanius requested changes

2022-08-18 10:55 UTC, DrGermanius commented on internal/handlers/auth_handlers.go
> +		h.sendErrorResponse(ctx, usererrors.ErrorToCode(err), responses.NewServerRequestError(fmt.Sprint(err)))
im still don't understand the purpose of Sprint

2022-08-18 10:55 UTC, DrGermanius commented on internal/handlers/middlewares.go
> +	ctx.Next()
is that call necessary ?

2022-08-18 10:55 UTC, DrGermanius commented on internal/services/service.go
> +	}
it's bad solution because what if you have an error during GetUserByPhone call?

2022-08-18 11:11 UTC, Kalasouski commented on internal/handlers/auth_handlers.go
> +		h.sendErrorResponse(ctx, usererrors.ErrorToCode(err), responses.NewServerRequestError(fmt.Sprint(err)))
I forgot to delete Sprint in one place

2022-08-22 19:04 UTC, DrGermanius approved these changes
for the following tasks create an another PR

2022-08-22 19:14 UTC, merged